@startuml
!include ../../00_Comun/00.0_Estilo_Comun.iuml


' FASE ELABORATION

start
:Planeamiento de Iteración;
fork
    :<center>Identificar y\nRefinar Requisitos;
    note right:<center>Se desarrolla en\nel Meta-Modelo del Proceso\nde Ingeniería de Requisitos
fork again
    :<center>Desarrollar la\nArquitectura;
    note right:<center>Se desarrolla en\nel Meta-Modelo del\nProceso de Diseño
fork again
    :<center>Configurar y Refinar\nMemoria Persistente;
fork again
    :<center>Desarrollar documentación\ndel proyecto;
endfork
stop

@enduml
