---
title: Meta-modelo de Diseño
config:
    layout: elk
    class:
        hideEmptyMembersBox: true
---

classDiagram
class Arquitecto["Arquitecto"]:::rol {
    <<Rol>>
}

class ArquitecturaSoftware["Arquitectura de Software"]:::artefacto {
    <<Artefacto>>
}

class PatronesDisenio["Patrón de Diseño"]:::artefacto {
    <<Artefacto>>
}

class BaseDatos["Modelo de Base de Datos"]:::artefacto {
    <<Artefacto>>
}

class Interfaz["Interfaz"]:::artefacto {
    <<Artefacto>>
}

%% === RELACIONES ===

Arquitecto --> ArquitecturaSoftware : Evalúa alternativas
Arquitecto --> PatronesDisenio : Evalúa alternativas
Arquitecto --> BaseDatos               : Diseña
Arquitecto --> Interfaz          : Diseña

classDef proceso fill:#3d3d3a,stroke:#2C2C2A,color:#F1EFE8
classDef fase fill:#c4a336,stroke:#8a6f1f,color:#1a1400
classDef disciplina fill:#c47b36,stroke:#7a4a1d,color:#1a0f00
classDef evento fill:#a45be9,stroke:#6a2fa8,color:#1a0033
classDef rol fill:#534AB7,stroke:#2c2570,color:#eeeeff
classDef artefacto fill:#36b3c4,stroke:#1d6e7a,color:#001a1e